# Generated by Django 4.2.10 on 2024-03-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(choices=[(1, 'Fist'), (2, 'Second'), (3, 'Third')], unique=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HowToUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(choices=[(1, 'Fist'), (2, 'Second'), (3, 'Third')], unique=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_on'],
            },
        ),
    ]
