# Generated by Django 4.2.10 on 2024-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='howtouse',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='author',
            field=models.TextField(max_length=100),
        ),
    ]
