# Generated by Django 4.2.10 on 2024-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_features_title_alter_howtouse_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='display_order',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], unique=True),
        ),
        migrations.AlterField(
            model_name='howtouse',
            name='display_order',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], unique=True),
        ),
    ]
