# Generated by Django 4.2.10 on 2024-03-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_category_category_name_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'due_at', '-priority', 'created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='due_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='featured_image',
            new_name='image',
        ),
    ]
